cheeseItVS2015/Models/Cheese.cs
using System;

namespace cheeseItVS2015.Models
{
    public static class CheeseConstants
    {
        public static readonly Decimal MAX_PRICE = 20M;
        public static readonly Decimal STANARD_PRICE_DECREASE_RATE = -0.05M;
        public static readonly Decimal FRESH_PRICE_DECREASE_RATE = -0.1M;
        public static readonly Decimal AGED_PRICE_INCREASE_RATE = 0.05M;
        public static readonly Decimal SPECIAL_PRICE_INCREASE_RATE = 0.05M;
    }

    public enum CheeseType
    {
        Fresh,
        Unique,
        Special,
        Aged,
        Standard
    }

    public class Cheese
    {
        public string Name { get; set; }
        public DateTime DateRecieved { get; set; }
        public DateTime? BestBeforeDate { get; set; }
        public int? DaysToSell { get; set; }
        public Decimal? Price { get; set; }
        public CheeseType Type { get; set; }

        public Decimal? PriceForDay(DateTime day)
        {
            if (Price == null || DateRecieved == DateTime.MinValue)
            {
                return null;
            }
            var daysOld = Convert.ToDecimal((day.Date - DateRecieved.Date).TotalDays);

            if (Type != CheeseType.Unique && daysOld > DaysToSell)
            {
                return null;
            }

            var changeRate = ChangeRate(day, daysOld);
            var calculatedPrice = Price + Price * changeRate * daysOld;
            if (calculatedPrice > CheeseConstants.MAX_PRICE)
            {
                return CheeseConstants.MAX_PRICE;
            }
            if (calculatedPrice < 0)
            {
                return 0M;
            }
            return calculatedPrice;
        }

        private Decimal ChangeRate(DateTime day, Decimal daysOld)
        {
            var changeRate = CheeseConstants.STANARD_PRICE_DECREASE_RATE;
            var bestBeforeChangeRate = 2;
            switch (Type)
            {
                case (CheeseType.Aged):
                    changeRate = CheeseConstants.AGED_PRICE_INCREASE_RATE;
                    bestBeforeChangeRate = 1;
                    break;
                case (CheeseType.Unique):
                    changeRate = 0;
                    break;
                case (CheeseType.Fresh):
                    changeRate = CheeseConstants.FRESH_PRICE_DECREASE_RATE;
                    break;
                case (CheeseType.Special):
                    changeRate = CheeseConstants.SPECIAL_PRICE_INCREASE_RATE;
                    if (DaysToSell - daysOld < 6)
                    {
                        changeRate = CheeseConstants.SPECIAL_PRICE_INCREASE_RATE * 2;
                    }
                    break;
                default:
                    changeRate = CheeseConstants.STANARD_PRICE_DECREASE_RATE;
                    break;
            }
            if (BestBeforeDate != null && Type != CheeseType.Special)
            {
                DateTime nonNullBestBefore = BestBeforeDate ?? DateTime.Now;
                if (nonNullBestBefore.Date < day.Date)
                {
                    changeRate = changeRate * bestBeforeChangeRate;
                }
            }
            return changeRate;
        }
    }
}

cheeseItVS2015/Models/CheeseViewModel.cs
using System;
using System.Collections.Generic;

namespace cheeseItVS2015.Models
{
    public class CheeseViewModel
    {
        public ICollection<Cheese> Cheeses { get; set; }
        public Dictionary<String, List<Decimal?>> FutureCheesePrices { get; set; }
        public String Message { get; set; }
    }
}

cheeseItVS2015/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace cheeseItVS2015.Models
{
    [XmlRoot("Items")]
    public class ItemCollection
    {
        [XmlElement("Item")]
        public List<Item> Items { get; set; }
    }

    public class Item
    {
        public string Name { get; set; }
        public string BestBeforeDate { get; set; }
        public string DaysToSell { get; set; }
        public string Price { get; set; }
        public string Type { get; set; }
    }

    public class Container
    {
        public Item[] Items { get; set; }
    }
}

cheeseItVS2015/Controllers/CheeseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cheeseItVS2015.Models;
using cheeseItVS2015.Repositories;
using cheeseItVS2015.Services;

namespace cheeseItVS2015.Controllers
{
    public class CheeseController : Controller
    {
        private readonly ICheeseService _cheeseService;

        public CheeseController()
        {
            var cheeseRepo = CheeseRepositoryFactory.SharedInstance();
            _cheeseService = new CheeseService(cheeseRepo);
        }

        // GET: /<controller>/
        public ActionResult Index()
        {
            var cheeses = _cheeseService.GetAllCheeses().ToArray();
            var futureCheesePrices = _cheeseService.FutureCheesePrices(7);

            var message = "";
            if (cheeses.Length == 0)
            {
                message = "There are no cheeses loaded yet, please load some cheeses";
            }

            var viewModel = new CheeseViewModel
            {
                Cheeses = cheeses,
                FutureCheesePrices = futureCheesePrices,
                Message = message
            };
            return View(viewModel);
        }
    }
}

cheeseItVS2015/Controllers/LoadFileController.cs
using System;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using cheeseItVS2015.Repositories;
using cheeseItVS2015.Services;

namespace cheeseItVS2015.Controllers
{
    public class LoadFileController : Controller
    {
        private readonly ICheeseLoaderService _cheeseService;

        public LoadFileController()
        {
            var cheeseRepo = CheeseRepositoryFactory.SharedInstance();
            _cheeseService = new CheeseLoaderService(cheeseRepo);
        }

        // GET: /<controller>/
        public ActionResult Load()
        {
            return View();
        }

        // POST: LoadFile/Load
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Load(HttpPostedFileBase file)
        {
            if (file?.FileName != null)
            {
                var recievedDate = DateFromFileName(file.FileName);
                if (recievedDate == DateTime.MinValue)
                {
                    ViewBag.result = "Please Enter a file with a valid file format.";
                    ViewBag.resultCssClass = "alert alert-danger";
                    ViewBag.showLink = false;
                }
                else
                {
                    try
                    {
                        if (file.ContentLength > 0)
                        {
                            var numCheesesLoaded = _cheeseService.LoadCheeses(file, recievedDate);

                            ViewBag.result = $"Successfully loaded {numCheesesLoaded} Cheeses.";
                            ViewBag.resultCssClass = "alert alert-success";
                            ViewBag.showLink = true;
                        }
                        else
                        {
                            ViewBag.result = "No Cheeses loaded.";
                            ViewBag.resultCssClass = "alert alert-warning";
                            ViewBag.showLink = false;
                        }
                    }
                    catch (Exception)
                    {
                        ViewBag.result = "There was a problem with the your Cheese file. Please try a different file.";
                        ViewBag.resultCssClass = "alert alert-danger";
                        ViewBag.showLink = false;
                    }
                }
            }

            return View();
        }

        private DateTime DateFromFileName(string fileName)
        {
            DateTime fileDate;

            var dateString = "";
            if (fileName.IndexOf("_") > 0 && fileName.IndexOf(".xml") > 0)
            {
                try
                {
                    var dateWithExtension = fileName.Substring(fileName.IndexOf("_") + 1, fileName.Length - fileName.IndexOf("_") - 1);
                    dateString = dateWithExtension.Substring(0, dateWithExtension.IndexOf(".xml"));
                }
                catch (Exception)
                {
                }
            }
            
            DateTime.TryParseExact(dateString, "ddMMyyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out fileDate);

            return fileDate;
        }
    }
}

cheeseItVS2015/Views/Cheese/Index.cshtml
@model cheeseItVS2015.Models.CheeseViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Load New Cheeses</h2>
<p>
    @Html.ActionLink("Load Cheese File", "Load", "LoadFile")
</p>
<hr />

@if (!string.IsNullOrWhiteSpace(Model.Message))
{
    <h2>@Model.Message</h2>
}

@if (Model.Cheeses.Count > 0)
{
    <h2>Cheese List</h2>
    <p class="alert alert-info">Note: Cheese prices are displayed in Gold Pieces.Silver Pieces for conciseness.</p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Date Received
                </th>
                <th>
                    Best Before Date
                </th>
                <th>
                    Days To Sell
                </th>
                <th>
                    Original Price
                </th>
                <th>
                    Type
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cheeses)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @item.DateRecieved.ToString("MM/dd/yyyy")
                    </td>
                    <td>
                        @if (item.BestBeforeDate.HasValue)
                        {
                            @item.BestBeforeDate.Value.ToString("MM/dd/yyyy")
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DaysToSell)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                </tr>   }
        </tbody>
    </table>

    <h2>Future Cheese Prices</h2>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    1 Day Old
                </th>
                <th>
                    2 Days Old
                </th>
                <th>
                    3 Days Old
                </th>
                <th>
                    4 Days Old
                </th>
                <th>
                    5 Days Old
                </th>
                <th>
                    6 Days Old
                </th>
                <th>
                    7 Days Old
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (KeyValuePair<string, List<Decimal?>> pair in Model.FutureCheesePrices)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => pair.Key)
                    </td>
                    @foreach (var item in pair.Value)
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item)
                        </td>
                    }
                </tr>   }
        </tbody>
    </table>
}

cheeseItVS2015/Views/LoadFile/Load.cshtml
@{
    ViewData["Title"] = "Load Cheese File";
}

<h2>Load Cheeses</h2>

<div class="form-horizontal">
    <hr />
@if (ViewBag.result != null)
{
    <p class="@ViewBag.resultCssClass">@ViewBag.result 
        @if (ViewBag.showLink)
        {
            @Html.ActionLink("Back To Cheese List", "Index", "Cheese")
        }
    </p>
}

@using (Html.BeginForm("Load", "LoadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <span class="text-warning">File must be in the format of name_ddMMyyyy.xml</span>
    <div class="form-group">        
        <label class="col-md-2 control-label">File</label>
        <div class="col-md-10">
            @Html.TextBox("file", "", new {type = "file", required="required"})
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Load" class="btn btn-default"/>
        </div>
    </div>
}
</div>


<div>
    @Html.ActionLink("Back To Cheese List", "Index", "Cheese")
</div>

cheeseItVS2015/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - cheeseIt</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("cheeseIt", "Index", "cheese", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Load Cheese File", "Load", "LoadFile")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -cheeseIt</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>